---
# yaml-language-server: $schema=https://www.schemastore.org/kustomization.json
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: external-secrets
components:
- ../../components/app-template
resources:
- ./namespace.yaml
- ./external-secrets/app.yaml
- ./onepassword-connect/app.yaml
