---
# yaml-language-server: $schema=https://kubernetes-schemas.mcf.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vsphere-cloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: vsphere-cloud-secret
    template:
      data:
        192.168.1.15.username: "{{ .username }}"
        192.168.1.15.password: "{{ .password }}"
  dataFrom:
  - extract:
      key: vsphere-cloud
