---
# yaml-language-server: $schema=https://kubernetes-schemas.mcf.io/source.toolkit.fluxcd.io/gitrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: vsphere-cpi
spec:
  interval: 15m
  url: https://github.com/kubernetes/cloud-provider-vsphere
  ref:
    branch: release-1.34
