---
# yaml-language-server: $schema=https://kubernetes-schemas.mcf.io/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vsphere-cpi
spec:
  interval: 12h
  chart:
    spec:
      chart: ./charts/vsphere-cpi
      sourceRef:
        kind: GitRepository
        name: vsphere-cpi
