---
# yaml-language-server: $schema=https://kubernetes-schemas.mcf.io/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: onepassword-connect
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: onepassword-connect-secret
    creationPolicy: Merge
    template:
      data:
        1password-credentials.json: "{{ .CREDENTIAL }}"
        token: "{{ .TOKEN }}"
  dataFrom:
  - extract:
      key: onepassword-connect
